# -*- coding: utf-8 -*-
# Translations for CloudRegen — loaded via exec() from generate-lang.py

# --- Spanish ---
L("es",
    prefix="&8[&bCloudRegen&8] &7",
    no_permission="&cSin permiso.",
    player_only="&cSolo los jugadores pueden usar este comando.",
    unknown_subcommand="&cSubcomando desconocido. Usa /cr help.",
    help=help_lines(
        "&b☁ &fCloudRegen &8- &7Centro de comandos",
        "&7/cr help &8- &fMostrar este menú",
        "&7/cr wand &8- &fObtener varita de selección",
        "&7/cr save [name] &8- &fGuardar región seleccionada",
        "&7/cr redefine <name> &8- &fRedefinir región existente",
        "&7/cr editor &8- &fAbrir explorador de regiones",
        "&7/cr edit <name> &8- &fAbrir editor de región directamente",
        "&7/cr force <name> &8- &fForzar regeneración ahora",
        "&7/cr list &8- &fListar regiones guardadas",
        "&7/cr delete <name> &8- &fEliminar una región",
        "&7/cr reload &8- &fRecargar config e idioma",
        "&7/cr debug &8- &fMostrar estadísticas en tiempo real",
    ),
    actionbar_help="&b☁ &fComandos de CloudRegen listos",
    wand_given="&a✨ Varita de selección entregada.",
    actionbar_wand_given="&b☁ &fVarita equipada",
    selection_pos1="&bPos1 establecida: &f%x%, %y%, %z%",
    selection_pos2="&bPos2 establecida: &f%x%, %y%, %z%",
    selection_pos1_actionbar="&bPos1 &8➜ &f%x% &7%y% &f%z%",
    selection_pos2_actionbar="&bPos2 &8➜ &f%x% &7%y% &f%z%",
    need_selection="&cSelecciona dos posiciones primero.",
    save_name_prompt="&eEscribe el nombre de la región en el chat o escribe cancel.",
    region_saved="&aRegión guardada: &f%name%",
    region_redefined="&aRegión redefinida: &f%name%",
    region_save_failed="&cError al guardar la región: &f%name%",
    region_load_failed="&cError al cargar la instantánea de la región: &f%name%",
    title_saved="&aRegión guardada",
    subtitle_saved="&fInstantánea almacenada correctamente",
    title_redefined="&aRegión redefinida",
    subtitle_redefined="&fInstantánea reemplazada correctamente",
    actionbar_saved="&aGuardada &f%name%",
    region_not_found="&cRegión no encontrada.",
    region_world_missing="&cEl mundo de la región no está disponible.",
    region_deleted="&aRegión eliminada: &f%name%",
    region_forced="&aRegeneración forzada para: &f%name%",
    title_force="&eRegeneración forzada",
    subtitle_force="&fLa región ha sido puesta en cola",
    redefine_usage="&eUso: /cr redefine <name>",
    edit_usage="&eUso: /cr edit <name>",
    force_usage="&eUso: /cr force <name>",
    delete_usage="&eUso: /cr delete <name>",
    reloaded="&aCloudRegen recargado.",
    list_header="&bRegiones (&f%count%&b):",
    list_entry="&7- &f%name% &8| &b%mode% &8| &f%interval%s",
    list_empty="&eAún no se han creado regiones.",
    editor_opened="&aExplorador de regiones abierto.",
    editor_empty="&eNo hay regiones para mostrar en el editor.",
    browser_closed="&7Explorador de regiones cerrado.",
    edit_opened="&aEditor de región abierto para &f%name%",
    editor_input_display="&eEscribe el nuevo nombre visible en el chat o cancela.",
    editor_input_interval="&eEscribe el nuevo intervalo (segundos) o cancela.",
    editor_input_message="&eEscribe el mensaje de la región, 'null' para desactivar, o cancela.",
    editor_display_updated="&aNombre visible actualizado.",
    editor_interval_updated="&aIntervalo actualizado a &f%value%s&a.",
    editor_mode_updated="&aModo establecido en &f%value%&a.",
    editor_message_updated="&aMensaje de región actualizado.",
    editor_safety_updated="&aTeletransporte de seguridad alternado: &f%value%",
    editor_audience_updated="&aAudiencia del mensaje establecida en: &f%value%",
    editor_teleported="&aTeletransportado a la posición inicial de la región.",
    editor_saved="&aCambios del editor guardados.",
    editor_closed="&7Editor cerrado.",
    invalid_number="&cNúmero no válido.",
    input_cancelled="&eEntrada cancelada.",
    regen_message_format="&8[&bRegen&8] &7%region% &8» &f%message%",
    actionbar_regen="&aRegión regenerada: &f%region%",
    actionbar_safety_teleport="&eMovido a un lugar seguro durante la regeneración",
    debug_header="&8&m--------------- &bCloudRegen Debug &8&m---------------",
    debug_active="&7Regeneraciones activas: &f%value%",
    debug_queued="&7Bloques en cola: &f%value%",
    debug_applied="&7Total aplicados: &f%value%",
    debug_regens="&7Regeneraciones totales: &f%value%",
    debug_rate="&7Prom. bloques/seg: &f%value%",
    debug_budget="&7Presupuesto del ciclo: &f%value%",
    debug_complete="&aInstantánea de depuración enviada.",
    language_fallback="&eArchivo de idioma no encontrado. Usando inglés (en).",
)

# --- Russian ---
L("ru",
    prefix="&8[&bCloudRegen&8] &7",
    no_permission="&cНет прав доступа.",
    player_only="&cЭту команду могут использовать только игроки.",
    unknown_subcommand="&cНеизвестная подкоманда. Используйте /cr help.",
    help=help_lines(
        "&b☁ &fCloudRegen &8- &7Центр команд",
        "&7/cr help &8- &fПоказать это меню",
        "&7/cr wand &8- &fПолучить инструмент выделения",
        "&7/cr save [name] &8- &fСохранить выделенный регион",
        "&7/cr redefine <name> &8- &fПереопределить существующий регион",
        "&7/cr editor &8- &fОткрыть браузер регионов",
        "&7/cr edit <name> &8- &fОткрыть редактор региона напрямую",
        "&7/cr force <name> &8- &fПринудительно запустить регенерацию",
        "&7/cr list &8- &fСписок сохранённых регионов",
        "&7/cr delete <name> &8- &fУдалить регион",
        "&7/cr reload &8- &fПерезагрузить конфиг и язык",
        "&7/cr debug &8- &fПоказать статистику в реальном времени",
    ),
    actionbar_help="&b☁ &fКоманды CloudRegen готовы",
    wand_given="&a✨ Инструмент выделения выдан.",
    actionbar_wand_given="&b☁ &fИнструмент экипирован",
    selection_pos1="&bPos1 установлена: &f%x%, %y%, %z%",
    selection_pos2="&bPos2 установлена: &f%x%, %y%, %z%",
    selection_pos1_actionbar="&bPos1 &8➜ &f%x% &7%y% &f%z%",
    selection_pos2_actionbar="&bPos2 &8➜ &f%x% &7%y% &f%z%",
    need_selection="&cСначала выделите две позиции.",
    save_name_prompt="&eВведите имя региона в чат или напишите cancel.",
    region_saved="&aРегион сохранён: &f%name%",
    region_redefined="&aРегион переопределён: &f%name%",
    region_save_failed="&cНе удалось сохранить регион: &f%name%",
    region_load_failed="&cНе удалось загрузить снимок региона: &f%name%",
    title_saved="&aРегион сохранён",
    subtitle_saved="&fСнимок успешно сохранён",
    title_redefined="&aРегион переопределён",
    subtitle_redefined="&fСнимок успешно заменён",
    actionbar_saved="&aСохранено &f%name%",
    region_not_found="&cРегион не найден.",
    region_world_missing="&cМир региона недоступен.",
    region_deleted="&aРегион удалён: &f%name%",
    region_forced="&aПринудительная регенерация для: &f%name%",
    title_force="&eПринудительная регенерация",
    subtitle_force="&fРегион поставлен в очередь",
    redefine_usage="&eИспользование: /cr redefine <name>",
    edit_usage="&eИспользование: /cr edit <name>",
    force_usage="&eИспользование: /cr force <name>",
    delete_usage="&eИспользование: /cr delete <name>",
    reloaded="&aCloudRegen перезагружен.",
    list_header="&bРегионы (&f%count%&b):",
    list_entry="&7- &f%name% &8| &b%mode% &8| &f%interval%s",
    list_empty="&eРегионы ещё не созданы.",
    editor_opened="&aБраузер регионов открыт.",
    editor_empty="&eНет регионов для отображения в редакторе.",
    browser_closed="&7Браузер регионов закрыт.",
    edit_opened="&aРедактор региона открыт для &f%name%",
    editor_input_display="&eВведите новое отображаемое имя в чат или cancel.",
    editor_input_interval="&eВведите новый интервал (секунды) или cancel.",
    editor_input_message="&eВведите сообщение региона, 'null' для отключения, или cancel.",
    editor_display_updated="&aОтображаемое имя обновлено.",
    editor_interval_updated="&aИнтервал обновлён до &f%value%s&a.",
    editor_mode_updated="&aРежим установлен: &f%value%&a.",
    editor_message_updated="&aСообщение региона обновлено.",
    editor_safety_updated="&aБезопасный телепорт переключён: &f%value%",
    editor_audience_updated="&aАудитория сообщений установлена: &f%value%",
    editor_teleported="&aТелепортирован на начальную позицию региона.",
    editor_saved="&aИзменения редактора сохранены.",
    editor_closed="&7Редактор закрыт.",
    invalid_number="&cНеверное число.",
    input_cancelled="&eВвод отменён.",
    regen_message_format="&8[&bRegen&8] &7%region% &8» &f%message%",
    actionbar_regen="&aРегион регенерирован: &f%region%",
    actionbar_safety_teleport="&eПеремещён в безопасное место во время регенерации",
    debug_header="&8&m--------------- &bCloudRegen Debug &8&m---------------",
    debug_active="&7Активные регенерации: &f%value%",
    debug_queued="&7Блоков в очереди: &f%value%",
    debug_applied="&7Всего применено: &f%value%",
    debug_regens="&7Всего регенераций: &f%value%",
    debug_rate="&7Сред. блоков/сек: &f%value%",
    debug_budget="&7Бюджет цикла: &f%value%",
    debug_complete="&aОтладочный снимок отправлен.",
    language_fallback="&eФайл языка не найден. Используется английский (en).",
)

# --- German ---
L("de",
    prefix="&8[&bCloudRegen&8] &7",
    no_permission="&cKeine Berechtigung.",
    player_only="&cNur Spieler können diesen Befehl nutzen.",
    unknown_subcommand="&cUnbekannter Unterbefehl. Nutze /cr help.",
    help=help_lines(
        "&b☁ &fCloudRegen &8- &7Kommandozentrale",
        "&7/cr help &8- &fDieses Menü anzeigen",
        "&7/cr wand &8- &fAuswahlwerkzeug erhalten",
        "&7/cr save [name] &8- &fAusgewählte Region speichern",
        "&7/cr redefine <name> &8- &fBestehende Region neu definieren",
        "&7/cr editor &8- &fRegionsbrowser öffnen",
        "&7/cr edit <name> &8- &fRegionseditor direkt öffnen",
        "&7/cr force <name> &8- &fRegeneration sofort erzwingen",
        "&7/cr list &8- &fGespeicherte Regionen auflisten",
        "&7/cr delete <name> &8- &fRegion löschen",
        "&7/cr reload &8- &fConfig und Sprache neu laden",
        "&7/cr debug &8- &fLaufzeitstatistiken anzeigen",
    ),
    actionbar_help="&b☁ &fCloudRegen-Befehle bereit",
    wand_given="&a✨ Auswahlwerkzeug erhalten.",
    actionbar_wand_given="&b☁ &fWerkzeug ausgerüstet",
    selection_pos1="&bPos1 gesetzt: &f%x%, %y%, %z%",
    selection_pos2="&bPos2 gesetzt: &f%x%, %y%, %z%",
    selection_pos1_actionbar="&bPos1 &8➜ &f%x% &7%y% &f%z%",
    selection_pos2_actionbar="&bPos2 &8➜ &f%x% &7%y% &f%z%",
    need_selection="&cWähle zuerst zwei Positionen aus.",
    save_name_prompt="&eGib den Regionsnamen im Chat ein oder tippe cancel.",
    region_saved="&aRegion gespeichert: &f%name%",
    region_redefined="&aRegion neu definiert: &f%name%",
    region_save_failed="&cRegion konnte nicht gespeichert werden: &f%name%",
    region_load_failed="&cRegionssnapshot konnte nicht geladen werden: &f%name%",
    title_saved="&aRegion gespeichert",
    subtitle_saved="&fSnapshot erfolgreich gespeichert",
    title_redefined="&aRegion neu definiert",
    subtitle_redefined="&fSnapshot erfolgreich ersetzt",
    actionbar_saved="&aGespeichert &f%name%",
    region_not_found="&cRegion nicht gefunden.",
    region_world_missing="&cRegionswelt ist nicht verfügbar.",
    region_deleted="&aRegion gelöscht: &f%name%",
    region_forced="&aRegeneration erzwungen für: &f%name%",
    title_force="&eRegeneration erzwungen",
    subtitle_force="&fRegion wurde in die Warteschlange gestellt",
    redefine_usage="&eVerwendung: /cr redefine <name>",
    edit_usage="&eVerwendung: /cr edit <name>",
    force_usage="&eVerwendung: /cr force <name>",
    delete_usage="&eVerwendung: /cr delete <name>",
    reloaded="&aCloudRegen neu geladen.",
    list_header="&bRegionen (&f%count%&b):",
    list_entry="&7- &f%name% &8| &b%mode% &8| &f%interval%s",
    list_empty="&eEs wurden noch keine Regionen erstellt.",
    editor_opened="&aRegionsbrowser geöffnet.",
    editor_empty="&eKeine Regionen im Editor verfügbar.",
    browser_closed="&7Regionsbrowser geschlossen.",
    edit_opened="&aRegionseditor geöffnet für &f%name%",
    editor_input_display="&eGib den neuen Anzeigenamen im Chat ein oder cancel.",
    editor_input_interval="&eGib das neue Intervall (Sekunden) ein oder cancel.",
    editor_input_message="&eGib die Regionsnachricht ein, 'null' zum Deaktivieren, oder cancel.",
    editor_display_updated="&aAnzeigename aktualisiert.",
    editor_interval_updated="&aIntervall aktualisiert auf &f%value%s&a.",
    editor_mode_updated="&aModus gesetzt auf &f%value%&a.",
    editor_message_updated="&aRegionsnachricht aktualisiert.",
    editor_safety_updated="&aSicherheitsteleport umgeschaltet: &f%value%",
    editor_audience_updated="&aNachrichtenzielgruppe gesetzt auf: &f%value%",
    editor_teleported="&aZur Startposition der Region teleportiert.",
    editor_saved="&aEditor-Änderungen gespeichert.",
    editor_closed="&7Editor geschlossen.",
    invalid_number="&cUngültige Zahl.",
    input_cancelled="&eEingabe abgebrochen.",
    regen_message_format="&8[&bRegen&8] &7%region% &8» &f%message%",
    actionbar_regen="&aRegion regeneriert: &f%region%",
    actionbar_safety_teleport="&eWährend der Regeneration an einen sicheren Ort bewegt",
    debug_header="&8&m--------------- &bCloudRegen Debug &8&m---------------",
    debug_active="&7Aktive Regenerationen: &f%value%",
    debug_queued="&7Blöcke in Warteschlange: &f%value%",
    debug_applied="&7Gesamt angewendet: &f%value%",
    debug_regens="&7Regenerationen gesamt: &f%value%",
    debug_rate="&7Ø Blöcke/Sek.: &f%value%",
    debug_budget="&7Zyklusbudget: &f%value%",
    debug_complete="&aDebug-Snapshot gesendet.",
    language_fallback="&eSprachdatei nicht gefunden. Englisch (en) wird verwendet.",
)

# --- French ---
L("fr",
    prefix="&8[&bCloudRegen&8] &7",
    no_permission="&cPermission refusée.",
    player_only="&cSeuls les joueurs peuvent utiliser cette commande.",
    unknown_subcommand="&cSous-commande inconnue. Utilisez /cr help.",
    help=help_lines(
        "&b☁ &fCloudRegen &8- &7Centre de commandes",
        "&7/cr help &8- &fAfficher ce menu",
        "&7/cr wand &8- &fObtenir la baguette de sélection",
        "&7/cr save [name] &8- &fEnregistrer la région sélectionnée",
        "&7/cr redefine <name> &8- &fRedéfinir une région existante",
        "&7/cr editor &8- &fOuvrir le navigateur de régions",
        "&7/cr edit <name> &8- &fOuvrir l'éditeur de région directement",
        "&7/cr force <name> &8- &fForcer la régénération maintenant",
        "&7/cr list &8- &fLister les régions enregistrées",
        "&7/cr delete <name> &8- &fSupprimer une région",
        "&7/cr reload &8- &fRecharger la config et la langue",
        "&7/cr debug &8- &fAfficher les statistiques en direct",
    ),
    actionbar_help="&b☁ &fCommandes CloudRegen prêtes",
    wand_given="&a✨ Baguette de sélection accordée.",
    actionbar_wand_given="&b☁ &fBaguette équipée",
    selection_pos1="&bPos1 définie : &f%x%, %y%, %z%",
    selection_pos2="&bPos2 définie : &f%x%, %y%, %z%",
    selection_pos1_actionbar="&bPos1 &8➜ &f%x% &7%y% &f%z%",
    selection_pos2_actionbar="&bPos2 &8➜ &f%x% &7%y% &f%z%",
    need_selection="&cSélectionnez d'abord deux positions.",
    save_name_prompt="&eTapez le nom de la région dans le chat ou cancel.",
    region_saved="&aRégion enregistrée : &f%name%",
    region_redefined="&aRégion redéfinie : &f%name%",
    region_save_failed="&cÉchec de l'enregistrement de la région : &f%name%",
    region_load_failed="&cÉchec du chargement de l'instantané : &f%name%",
    title_saved="&aRégion enregistrée",
    subtitle_saved="&fInstantané enregistré avec succès",
    title_redefined="&aRégion redéfinie",
    subtitle_redefined="&fInstantané remplacé avec succès",
    actionbar_saved="&aEnregistrée &f%name%",
    region_not_found="&cRégion introuvable.",
    region_world_missing="&cLe monde de la région est indisponible.",
    region_deleted="&aRégion supprimée : &f%name%",
    region_forced="&aRégénération forcée pour : &f%name%",
    title_force="&eRégénération forcée",
    subtitle_force="&fLa région a été mise en file d'attente",
    redefine_usage="&eUtilisation : /cr redefine <name>",
    edit_usage="&eUtilisation : /cr edit <name>",
    force_usage="&eUtilisation : /cr force <name>",
    delete_usage="&eUtilisation : /cr delete <name>",
    reloaded="&aCloudRegen rechargé.",
    list_header="&bRégions (&f%count%&b) :",
    list_entry="&7- &f%name% &8| &b%mode% &8| &f%interval%s",
    list_empty="&eAucune région n'a encore été créée.",
    editor_opened="&aNavigateur de régions ouvert.",
    editor_empty="&eAucune région à afficher dans l'éditeur.",
    browser_closed="&7Navigateur de régions fermé.",
    edit_opened="&aÉditeur de région ouvert pour &f%name%",
    editor_input_display="&eTapez le nouveau nom affiché dans le chat ou cancel.",
    editor_input_interval="&eTapez le nouvel intervalle (secondes) ou cancel.",
    editor_input_message="&eTapez le message de région, 'null' pour désactiver, ou cancel.",
    editor_display_updated="&aNom affiché mis à jour.",
    editor_interval_updated="&aIntervalle mis à jour : &f%value%s&a.",
    editor_mode_updated="&aMode défini sur &f%value%&a.",
    editor_message_updated="&aMessage de région mis à jour.",
    editor_safety_updated="&aTéléportation de sécurité basculée : &f%value%",
    editor_audience_updated="&aAudience des messages définie sur : &f%value%",
    editor_teleported="&aTéléporté à la position de départ de la région.",
    editor_saved="&aModifications de l'éditeur enregistrées.",
    editor_closed="&7Éditeur fermé.",
    invalid_number="&cNombre invalide.",
    input_cancelled="&eSaisie annulée.",
    regen_message_format="&8[&bRegen&8] &7%region% &8» &f%message%",
    actionbar_regen="&aRégion régénérée : &f%region%",
    actionbar_safety_teleport="&eDéplacé en lieu sûr pendant la régénération",
    debug_header="&8&m--------------- &bCloudRegen Debug &8&m---------------",
    debug_active="&7Régénérations actives : &f%value%",
    debug_queued="&7Blocs en file : &f%value%",
    debug_applied="&7Total appliqués : &f%value%",
    debug_regens="&7Régénérations totales : &f%value%",
    debug_rate="&7Moy. blocs/sec : &f%value%",
    debug_budget="&7Budget du cycle : &f%value%",
    debug_complete="&aInstantané de débogage envoyé.",
    language_fallback="&eFichier de langue introuvable. Anglais (en) utilisé.",
)

# --- Portuguese (Brazilian) ---
L("pt",
    prefix="&8[&bCloudRegen&8] &7",
    no_permission="&cSem permissão.",
    player_only="&cApenas jogadores podem usar este comando.",
    unknown_subcommand="&cSubcomando desconhecido. Use /cr help.",
    help=help_lines(
        "&b☁ &fCloudRegen &8- &7Central de comandos",
        "&7/cr help &8- &fMostrar este menu",
        "&7/cr wand &8- &fObter varinha de seleção",
        "&7/cr save [name] &8- &fSalvar região selecionada",
        "&7/cr redefine <name> &8- &fRedefinir região existente",
        "&7/cr editor &8- &fAbrir navegador de regiões",
        "&7/cr edit <name> &8- &fAbrir editor de região diretamente",
        "&7/cr force <name> &8- &fForçar regeneração agora",
        "&7/cr list &8- &fListar regiões salvas",
        "&7/cr delete <name> &8- &fExcluir uma região",
        "&7/cr reload &8- &fRecarregar config e idioma",
        "&7/cr debug &8- &fMostrar estatísticas em tempo real",
    ),
    actionbar_help="&b☁ &fComandos CloudRegen prontos",
    wand_given="&a✨ Varinha de seleção concedida.",
    actionbar_wand_given="&b☁ &fVarinha equipada",
    selection_pos1="&bPos1 definida: &f%x%, %y%, %z%",
    selection_pos2="&bPos2 definida: &f%x%, %y%, %z%",
    selection_pos1_actionbar="&bPos1 &8➜ &f%x% &7%y% &f%z%",
    selection_pos2_actionbar="&bPos2 &8➜ &f%x% &7%y% &f%z%",
    need_selection="&cSelecione duas posições primeiro.",
    save_name_prompt="&eDigite o nome da região no chat ou cancel.",
    region_saved="&aRegião salva: &f%name%",
    region_redefined="&aRegião redefinida: &f%name%",
    region_save_failed="&cFalha ao salvar região: &f%name%",
    region_load_failed="&cFalha ao carregar snapshot da região: &f%name%",
    title_saved="&aRegião salva",
    subtitle_saved="&fSnapshot armazenado com sucesso",
    title_redefined="&aRegião redefinida",
    subtitle_redefined="&fSnapshot substituído com sucesso",
    actionbar_saved="&aSalva &f%name%",
    region_not_found="&cRegião não encontrada.",
    region_world_missing="&cO mundo da região está indisponível.",
    region_deleted="&aRegião excluída: &f%name%",
    region_forced="&aRegeneração forçada para: &f%name%",
    title_force="&eRegeneração forçada",
    subtitle_force="&fRegião foi colocada na fila",
    redefine_usage="&eUso: /cr redefine <name>",
    edit_usage="&eUso: /cr edit <name>",
    force_usage="&eUso: /cr force <name>",
    delete_usage="&eUso: /cr delete <name>",
    reloaded="&aCloudRegen recarregado.",
    list_header="&bRegiões (&f%count%&b):",
    list_entry="&7- &f%name% &8| &b%mode% &8| &f%interval%s",
    list_empty="&eNenhuma região foi criada ainda.",
    editor_opened="&aNavegador de regiões aberto.",
    editor_empty="&eNenhuma região para exibir no editor.",
    browser_closed="&7Navegador de regiões fechado.",
    edit_opened="&aEditor de região aberto para &f%name%",
    editor_input_display="&eDigite o novo nome de exibição no chat ou cancel.",
    editor_input_interval="&eDigite o novo intervalo (segundos) ou cancel.",
    editor_input_message="&eDigite a mensagem da região, 'null' para desativar, ou cancel.",
    editor_display_updated="&aNome de exibição atualizado.",
    editor_interval_updated="&aIntervalo atualizado para &f%value%s&a.",
    editor_mode_updated="&aModo definido para &f%value%&a.",
    editor_message_updated="&aMensagem da região atualizada.",
    editor_safety_updated="&aTeleporte de segurança alternado: &f%value%",
    editor_audience_updated="&aPúblico da mensagem definido para: &f%value%",
    editor_teleported="&aTeleportado para a posição inicial da região.",
    editor_saved="&aAlterações do editor salvas.",
    editor_closed="&7Editor fechado.",
    invalid_number="&cNúmero inválido.",
    input_cancelled="&eEntrada cancelada.",
    regen_message_format="&8[&bRegen&8] &7%region% &8» &f%message%",
    actionbar_regen="&aRegião regenerada: &f%region%",
    actionbar_safety_teleport="&eMovido para um local seguro durante a regeneração",
    debug_header="&8&m--------------- &bCloudRegen Debug &8&m---------------",
    debug_active="&7Regenerações ativas: &f%value%",
    debug_queued="&7Blocos na fila: &f%value%",
    debug_applied="&7Total aplicados: &f%value%",
    debug_regens="&7Regenerações totais: &f%value%",
    debug_rate="&7Média blocos/seg: &f%value%",
    debug_budget="&7Orçamento do ciclo: &f%value%",
    debug_complete="&aSnapshot de debug enviado.",
    language_fallback="&eArquivo de idioma não encontrado. Usando inglês (en).",
)
